language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update
    - platformio lib install 28 64 415 44

script:
    - platformio run
